// <auto-generated />
namespace Duolingo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add001));
        
        string IMigrationMetadata.Id
        {
            get { return "202105081536594_Add001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
